Page({
  data:{
    good_index:null,
    good_detail:null,
    img_path:null,
  },
  onLoad:function(options){
    this.setData({
      good_detail:options.good_detail,
      good_id:options.good_id,
      img_path:"http://brucemarkdown.top:5000/image/"+options.img+'.jpg'
    });
  }
})